spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sweaterth
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.mail.ru
    username: soloveid87@mail.ru
    password: neCg93UGKb6k5cmqqENC
    port: 465
    protocol: smtps

mail.debug: false

upload.path: /C:/D/JavaP/sweaterThymeleaf/upload
