spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sweaterth
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

  mail:
    host: smtp.mail.ru
    username: soloveid87@mail.ru
    password: neCg93UGKb6k5cmqqENC
    port: 465
    protocol: smtps
    properties:
      mail:
        debug: true

graphql:
  altair:
    enabled: true
  annotations.base-package: graphql.kickstart.spring.boot.graphql.annotations
  schema-strategy: annotations
  graphiql:
    enabled: true

mail.debug: false

upload.path: /C:/D/JavaP/sweaterThymeleaf/upload
recaptcha.secret: 6LdjI7chAAAAANxOtTwE8hAmIv0kq1DJGR3i8qoZ

hostname: localhost:8080